### ISSUE TITLE
total_increasing 

### ISSUE THREAD

**Issue by djansen1987** [djansen1987/SAJeSolar#7]
![image](https://user-images.githubusercontent.com/20375973/132224618-fd63559b-b879-49c9-a3bd-292d01ac59d3.png)
https://developers.home-assistant.io/blog/2021/08/16/state_class_total/

**Comment by djansen1987** [comment]
Should be fixed in latest update

**Comment by LowKey88** [comment]
Hi @djansen1987 

Still getting same issue after updated. 

<img width="919" alt="Screenshot 2021-09-06 at 11 23 22 PM" src="https://user-images.githubusercontent.com/1294172/132238548-1a49e2b8-bd74-4d66-8392-6d3f335cc6ed.png">

**Comment by djansen1987** [comment]
Should be fixed in [v1.2.4](https://github.com/djansen1987/SAJeSolar/releases/tag/v1.2.4). Please see release notes for details.
Please let me know if this solves the Issue.
